name: Bedwars
description: Bedwars minigame by Karter Sanamo
version: '1.0.2'
main: com.kartersanamo.bedwars.Bedwars
api-version: '1.21'
author: Karter Sanamo
softdepend: [PlaceholderAPI, Multiverse-Core]

commands:
  bedwars:
    description: Main Bedwars command.
    aliases: [bw]
    usage: /bedwars <setup|reload|join|leave|start|forcestart|stop|cancel|list|npc>

permissions:
  bedwars.admin.setup:
    description: Use the in-world arena setup wizard (/bw setup).
    default: op
  bedwars.admin.reload:
    description: Reload arenas from disk (/bw reload).
    default: op
